apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cart-page-rs
  namespace: swasthik-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      key: cart
  template:
    metadata:
      labels:
        web: cart
    spec:
      containers:
        - name: cart-copntainer
          image: murulisocial123/cart-page-test:1.0
          port: 
            - containerPort: 3000
